### ISSUE TITLE
Footer mismatch

### ISSUE THREAD

**Issue by eko24ive** [Qwebeck/homework3#5]
Here is how your footer looks:
![image](https://cloud.githubusercontent.com/assets/25591824/22870037/9621409a-f1ac-11e6-8789-076eeccc6068.png)

And this is desirable result:
![image](https://cloud.githubusercontent.com/assets/25591824/22869215/0bc55978-f1a6-11e6-9f71-012a13476eef.png)

Please fix this.

**Comment by Qwebeck** [comment]
I add markers , but i can*t change list style and he looks like circle with border
How i can change it on point?

**Comment by eko24ive** [comment]
You can achieve this using `:before` pseudo-class:

```css
li a:before {
  content: "•";
  display: inline-block;
  width: 5px;
  color: ...
}
```
